export const SET_DATA_ALQURAN = 'SET_DATA_ALQURAN'
export const SET_DATA_ALQURAN_LOADING = 'SET_DATA_ALQURAN_LOADING'
export const SET_DATA_ALQURAN_ERROR = 'SET_DATA_ALQURAN_ERROR'

// detail
export const SET_DATADETAIL = 'SET_DATADETAIL'
export const SET_DATADETAIL_LOADING = 'SET_DATADETAIL_LOADING'
export const SET_DATADETAIL_ERROR = 'SET_DATADETAIL_ERROR'

// favorite
export const ADD_DATA_FAVORITE = 'ADD_DATA_FAVORITE'
export const ADD_DATA_FAVORITE_LOADING = 'ADD_DATA_FAVORITE_LOADING'
export const ADD_DATA_FAVORITE_ERROR = 'ADD_DATA_FAVORITE_ERROR'


export const SET_SEARCH = 'SET_SEARCH'